/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Cursor;
import javax.swing.JPanel;
import javax.swing.JTextField;
import ui.emailvalidator;
import static ui.pages.*;
import backend.otp;
import backend.CheckUser;

/**
 *
 * @author jhonr
 */
public class login extends javax.swing.JFrame {

    // Variables declaration - do not modify                     
    private javax.swing.JLabel email_label;
    public static javax.swing.JTextField email_textfield;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel login_label;
    private static javax.swing.JPanel loginpanel;
    private javax.swing.JLabel noaccount_label;
    private javax.swing.JLabel register_label;
    public static javax.swing.JLabel validator_label;
    private String temp_email;
    // End of variables declaration  

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        loginpanel = new javax.swing.JPanel();
        email_label = new javax.swing.JLabel();
        email_textfield = new javax.swing.JTextField();
        login_label = new javax.swing.JLabel();
        noaccount_label = new javax.swing.JLabel();
        register_label = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        validator_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(57, 55, 92));
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        loginpanel.setBackground(new java.awt.Color(57, 55, 92));

        email_label.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        email_label.setForeground(new java.awt.Color(255, 255, 255));
        email_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email_label.setText("E-mail :");
        email_label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        email_textfield.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        email_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_textfieldActionPerformed(evt);
            }
        });

        temp_email = email_textfield.getText();

        login_label.setBackground(new java.awt.Color(57, 55, 92));
        login_label.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        login_label.setForeground(new java.awt.Color(255, 255, 255));
        login_label.setText("Sign In");

        noaccount_label.setBackground(new java.awt.Color(57, 55, 92));
        noaccount_label.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        noaccount_label.setForeground(new java.awt.Color(255, 255, 255));
        noaccount_label.setText("No account?");

        register_label.setBackground(new java.awt.Color(57, 55, 92));
        register_label.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        register_label.setForeground(new java.awt.Color(255, 0, 0));
        register_label.setText("Register here");
        register_label.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        register_label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_labelMouseClicked(evt);
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_labelMouseEntered(evt);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register_labelMouseExited(evt);
            }
        });

        validator_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        validator_label.setForeground(new java.awt.Color(255, 0, 0));

        login_btn.setBackground(new java.awt.Color(99, 126, 107));
        login_btn.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        login_btn.setForeground(new java.awt.Color(255, 255, 255));
        login_btn.setText("Log In");
        login_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
        });
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginpanelLayout = new javax.swing.GroupLayout(loginpanel);
        loginpanel.setLayout(loginpanelLayout);
        loginpanelLayout.setHorizontalGroup(
                loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginpanelLayout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(loginpanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                                                .addComponent(login_btn)
                                                .addGap(315, 315, 315))
                                        .addGroup(loginpanelLayout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(loginpanelLayout.createSequentialGroup()
                                                                .addComponent(noaccount_label)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(register_label))
                                                        .addComponent(login_label)
                                                        .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(validator_label, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        loginpanelLayout.setVerticalGroup(
                loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginpanelLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(login_label)
                                .addGap(161, 161, 161)
                                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validator_label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(login_btn)
                                .addGap(60, 60, 60)
                                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(noaccount_label)
                                        .addComponent(register_label))
                                .addContainerGap(438, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(loginpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void register_labelMouseClicked(java.awt.event.MouseEvent evt) {
        pages.change("signup", "login");
    }

    private void register_labelMouseEntered(java.awt.event.MouseEvent evt) {
        register_label.setForeground(new java.awt.Color(255, 255, 153));
    }

    private void register_labelMouseExited(java.awt.event.MouseEvent evt) {
        register_label.setForeground(new java.awt.Color(255, 0, 0));
    }

    private void email_textfieldActionPerformed(java.awt.event.ActionEvent evt) {

    }

    protected static void login_btnMouseClicked(java.awt.event.MouseEvent evt) {
        if (emailvalidator.isValid(email_textfield.getText())) {
            int state = CheckUser.checkEmail(email_textfield.getText(),"login");
            if (verification.approve == 1) {
                pages.change("home", "login");
            } else if (state == 1) {
                
                otp.sendOtp(email_textfield.getText());
                pages.change("verification", "login");
            } else {
                login.validator_label.setText("User does not exist");
            }

        } else {
            login.validator_label.setText("E-mail is not valid");
        }
    }

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    public static JPanel rtn_loginpanel() {
        login l = new login();
        l.initComponents();
        return loginpanel;
    }
}
